// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package smartmei_backend

type Tarifa struct {
	ID         string  `json:"id"`
	Data       string  `json:"data"`
	Descricao  string  `json:"descricao"`
	ValorReal  float64 `json:"valorReal"`
	ValorDolar float64 `json:"valorDolar"`
	ValorEuro  float64 `json:"valorEuro"`
}
